version: "3.2"

services:
  php-app:
    image: php-app
    build: . 
    ports:
      - "80:80"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PASS_FILE=/run/secrets/mysqlpasscode
      - MYSQL_USER_FILE=/run/secrets/mysqlusername
    volumes:
      - php-app-volume:/var/www/html
    secrets:
      - mysqlpasscode
      - mysqlusername
    depends_on:
      - mysql
      
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=test
    volumes:
      - mysql-volume:/var/lib/mysql 
      
volumes:
  php-app-volume:
    external: true
  mysql-volume:
    external: true
   
secrets:
  mysqlpasscode:
    file: pass.txt
  mysqlusername:
    file: username.txt  
